# Generated by Django 3.0.5 on 2020-09-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AjustesInventario',
            fields=[
                ('idAjuste', models.AutoField(primary_key=True, serialize=False)),
                ('producto', models.CharField(blank=True, max_length=255, null=True)),
                ('concepto', models.CharField(blank=True, max_length=255, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('usuario', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CierresPOS',
            fields=[
                ('idCierre', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('usuario', models.CharField(blank=True, max_length=255, null=True)),
                ('base', models.IntegerField(blank=True, null=True)),
                ('ventas', models.IntegerField(blank=True, null=True)),
                ('porcobrar', models.IntegerField(blank=True, null=True)),
                ('ajustes', models.IntegerField(blank=True, null=True)),
                ('devoluciones', models.IntegerField(blank=True, null=True)),
                ('pagosefectuados', models.IntegerField(blank=True, null=True)),
                ('carterapagada', models.IntegerField(blank=True, null=True)),
                ('valorcierre', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consecutivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=255, null=True)),
                ('prefijo', models.CharField(blank=True, max_length=255, null=True)),
                ('consecutivo', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('nombrealterno', models.CharField(blank=True, max_length=255, null=True)),
                ('codigoalterno', models.CharField(blank=True, max_length=255, null=True)),
                ('marca', models.CharField(blank=True, max_length=255, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('fechacreacion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=255, null=True)),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Terceros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=255, null=True)),
                ('celular', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketsPOS',
            fields=[
                ('idTicket', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('usuario', models.CharField(blank=True, max_length=255, null=True)),
                ('valor', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('idVenta', models.AutoField(primary_key=True, serialize=False)),
                ('producto', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('valor', models.IntegerField(blank=True, null=True)),
                ('usuario', models.CharField(blank=True, max_length=255, null=True)),
                ('cierre', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(blank=True, max_length=255, null=True)),
                ('docventa', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
