# Generated by Django 3.0.5 on 2020-09-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='id',
        ),
        migrations.AlterField(
            model_name='productos',
            name='codigo',
            field=models.CharField(default=88766678, max_length=255, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
