# Generated by Django 3.0.5 on 2020-09-20 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0002_auto_20200913_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryLine',
            fields=[
                ('idmove', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('usuario', models.CharField(blank=True, max_length=255, null=True)),
                ('modulo', models.CharField(blank=True, max_length=255, null=True)),
                ('accion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
