# Generated by Django 3.0.5 on 2020-09-20 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0005_compras_compras_general'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventas',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
