# Generated by Django 3.0.5 on 2020-09-20 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0006_auto_20200920_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ajustesinventario',
            old_name='cantidad',
            new_name='creditos',
        ),
        migrations.AddField(
            model_name='ajustesinventario',
            name='debitos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
