# Generated by Django 3.0.5 on 2020-09-21 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0008_auto_20200920_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terceros',
            name='id',
        ),
        migrations.AlterField(
            model_name='terceros',
            name='identificacion',
            field=models.CharField(default='', max_length=255, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
