# Generated by Django 3.0.5 on 2020-09-21 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0009_auto_20200920_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketspos',
            name='cliente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
