# Generated by Django 3.0.5 on 2020-09-26 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0010_ticketspos_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras_general',
            name='estado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
