# Generated by Django 3.0.5 on 2020-09-27 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0012_compras_general_nombre_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compras_general',
            name='nombre_proveedor',
        ),
        migrations.AlterField(
            model_name='compras_general',
            name='proveedor',
            field=models.ForeignKey(default='NULL', max_length=255, on_delete=django.db.models.deletion.CASCADE, to='Sales.Terceros'),
            preserve_default=False,
        ),
    ]
