# Generated by Django 3.0.5 on 2020-09-27 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0013_auto_20200926_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compras',
            name='estado',
        ),
    ]
