# Generated by Django 3.0.5 on 2020-09-29 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0014_remove_compras_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='producto',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='Sales.Productos'),
            preserve_default=False,
        ),
    ]
