# Generated by Django 3.0.5 on 2020-09-29 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0015_auto_20200928_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='doccompra',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Sales.Compras_General'),
            preserve_default=False,
        ),
    ]
