# Generated by Django 3.0.5 on 2020-10-01 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0016_auto_20200929_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_View',
            fields=[
                ('producto', models.CharField(db_column='codigo', max_length=255, primary_key=True, serialize=False)),
                ('costo_promedio', models.IntegerField(blank=True, db_column='costo_promedio', null=True)),
                ('costo_maximo', models.IntegerField(blank=True, db_column='costo_maximo', null=True)),
                ('costo_minimo', models.IntegerField(blank=True, db_column='costo_minimo', null=True)),
                ('stock', models.IntegerField(blank=True, db_column='stock', null=True)),
            ],
            options={
                'db_table': 'stock',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InfoProductos',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Sales.productos',),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='docventa',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Sales.TicketsPOS'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ventas',
            name='producto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Sales.Productos'),
            preserve_default=False,
        ),
    ]
