# Generated by Django 3.0.5 on 2020-10-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0017_auto_20201001_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='cierre',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='usuario',
        ),
        migrations.AddField(
            model_name='ticketspos',
            name='cierre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
