# Generated by Django 3.0.5 on 2020-10-01 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0018_auto_20201001_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos_Clientes',
            fields=[
                ('idPago', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('usuario', models.CharField(blank=True, max_length=255, null=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sales.TicketsPOS')),
            ],
        ),
    ]
