# Generated by Django 3.0.5 on 2020-10-04 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0019_pagos_clientes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock_View',
        ),
        migrations.DeleteModel(
            name='InfoProductos',
        ),
        migrations.AlterField(
            model_name='ticketspos',
            name='cliente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Sales.Terceros'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='InfoProductos',
            fields=[
                ('producto', models.CharField(db_column='codigo', max_length=255, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=255)),
                ('marca', models.CharField(db_column='marca', max_length=255)),
                ('precio', models.IntegerField(blank=True, db_column='precio', null=True)),
                ('costo_promedio', models.IntegerField(blank=True, db_column='costo_promedio', null=True)),
                ('costo_maximo', models.IntegerField(blank=True, db_column='costo_maximo', null=True)),
                ('costo_minimo', models.IntegerField(blank=True, db_column='costo_minimo', null=True)),
                ('stock', models.IntegerField(blank=True, db_column='stock', null=True)),
                ('estado', models.CharField(db_column='estado', max_length=255)),
                ('ubicacion', models.CharField(db_column='ubicacion', max_length=255)),
            ],
            options={
                'db_table': 'stock',
                'managed': False,
            },
        ),
    ]
