# Generated by Django 3.0.5 on 2020-10-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0021_auto_20201008_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos_clientes',
            name='cierre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
