# Generated by Django 3.0.5 on 2020-10-19 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0022_pagos_clientes_cierre'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyTickets',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Sales.ticketspos',),
        ),
        migrations.CreateModel(
            name='Devoluciones',
            fields=[
                ('idDevolucion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('usuario', models.CharField(blank=True, max_length=255, null=True)),
                ('valor', models.IntegerField(blank=True, null=True)),
                ('cierre', models.CharField(blank=True, max_length=255, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sales.Terceros')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sales.TicketsPOS')),
            ],
        ),
    ]
