# Generated by Django 3.0.5 on 2020-10-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0023_devoluciones_proxytickets'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjustesCaja',
            fields=[
                ('idAjuste', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=255, null=True)),
                ('valor', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario', models.CharField(blank=True, max_length=255, null=True)),
                ('cierre', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
