# Generated by Django 3.0.5 on 2020-10-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0024_ajustescaja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
