# Generated by Django 3.0.5 on 2021-04-05 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0025_auto_20201028_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajustesinventario',
            name='prod_ajuste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sales.Productos'),
        ),
    ]
